apiVersion: noxus/v4
exportOptions:
  setActiveOnImport: false
kind: Bundle
metadata:
  exportedAt: null
  exportedBy: null
  noxusVersion: null
  sourceWorkspace: andre@noxus.ai
  sourceWorkspaceId: a4974db4-51aa-496e-9055-293fea377886
