apiVersion: noxus/v4
kind: flow
metadata:
  description: null
  id: 1af18dc9-c99e-489b-b372-3ae28791fb2f
  labels: {}
  name: '123'
  slug: 123-1af18dc9
schemaVersion: 1
spec:
  edges:
  - from_id:
      connector_name: output
      node_id: fa0d6cf5-2463-49ed-95eb-89d1ca177a6c
    to_id:
      connector_name: inputs
      key: Input 1
      node_id: 5970a901-b594-4e3e-aa5a-12b5fba75a4c
  - from_id:
      connector_name: text_output
      node_id: 5970a901-b594-4e3e-aa5a-12b5fba75a4c
    to_id:
      connector_name: input
      node_id: f8834edd-5dfb-43b4-b88b-4717fbf38a2f
  - from_id:
      connector_name: text_output
      node_id: 5970a901-b594-4e3e-aa5a-12b5fba75a4c
    to_id:
      connector_name: variables
      key: Input 1
      node_id: df73dd09-49a5-4db6-8a20-cf31f594dad5
  nodes:
  - connector_config:
      inputs:
      - choices:
        - data_type: str
          is_list: false
        - data_type: number
          is_list: false
        - data_type: bool
          is_list: false
        - data_type: datetime
          is_list: false
        - data_type: object
          is_list: false
        - data_type: dict
          is_list: false
        - data_type: Image
          is_list: false
        - data_type: Audio
          is_list: false
        - data_type: File
          is_list: false
        configured_by: type
        definition:
          data_type: str
          is_list: false
        description: null
        label: Input
        name: input
        optional: false
        propagates_list: true
        rules:
        - config_source: type
          type: type_set_by
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_type_input
        visible: true
      outputs:
      - choices:
        - data_type: str
          is_list: false
        - data_type: number
          is_list: false
        - data_type: bool
          is_list: false
        - data_type: datetime
          is_list: false
        - data_type: object
          is_list: false
        - data_type: dict
          is_list: false
        - data_type: Image
          is_list: false
        - data_type: Audio
          is_list: false
        - data_type: File
          is_list: false
        definition:
          data_type: str
          is_list: false
        description: null
        label: Output
        name: output
        optional: false
        propagates_list: true
        rules:
        - config_source: type
          type: type_set_by
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_type_connector
        visible: true
    display:
      position:
        x: 425.66666666666663
        y: 369
      size: {}
    id: fa0d6cf5-2463-49ed-95eb-89d1ca177a6c
    name: Input 1
    node_config:
      label: Input 1
    type: InputNode
  - connector_config:
      inputs:
      - choices:
        - data_type: str
          is_list: false
        - data_type: number
          is_list: false
        - data_type: bool
          is_list: false
        - data_type: datetime
          is_list: false
        - data_type: object
          is_list: false
        - data_type: dict
          is_list: false
        - data_type: Image
          is_list: false
        - data_type: File
          is_list: false
        - data_type: Audio
          is_list: false
        definition:
          data_type: str
          is_list: false
        description: null
        label: Output Value
        name: input
        optional: false
        propagates_list: true
        rules:
        - config_source: type
          type: type_set_by
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_type_connector
        visible: true
      outputs:
      - choices:
        - data_type: str
          is_list: false
        - data_type: number
          is_list: false
        - data_type: bool
          is_list: false
        - data_type: datetime
          is_list: false
        - data_type: object
          is_list: false
        - data_type: dict
          is_list: false
        - data_type: Image
          is_list: false
        - data_type: File
          is_list: false
        - data_type: Audio
          is_list: false
        configured_by: type
        definition:
          data_type: str
          is_list: false
        description: null
        label: Output
        name: output
        optional: false
        propagates_list: true
        rules:
        - config_source: type
          type: type_set_by
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_type_output
        visible: true
    display:
      position:
        x: 1081.1666666666665
        y: 379.83333333333337
      size: {}
    id: f8834edd-5dfb-43b4-b88b-4717fbf38a2f
    name: Output 1
    node_config:
      label: Output 1
    type: OutputNode
  - connector_config:
      inputs:
      - choices:
        - data_type: str
          is_list: false
        - data_type: File
          is_list: false
        - data_type: dict
          is_list: false
        definition:
          data_type: str
          is_list: false
        description: null
        gathered_keys: []
        keys:
        - Input 1
        label: Input
        manual: true
        name: inputs
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_type_size_connector
        type_definitions:
          Input 1:
            data_type: str
            is_list: false
        visible: true
      outputs:
      - definition:
          data_type: str
          is_list: false
        description: null
        label: Response
        name: text_output
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: connector
        visible: true
      - allow_empty: false
        definition:
          data_type: str
          is_list: false
        description: null
        keys:
        - name
        label: Fields
        manual: false
        name: outputs
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_connector
        visible: false
      - definition:
          data_type: File
          is_list: false
        description: null
        label: Image
        name: image_output
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: connector
        visible: false
      - definition:
          data_type: str
          is_list: false
        description: null
        label: On error
        name: on_error
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: connector
        visible: false
    display:
      position:
        x: 676.9999999999999
        y: 493.16666666666663
      size: {}
    id: 5970a901-b594-4e3e-aa5a-12b5fba75a4c
    name: Generate Text
    node_config:
      json_fields:
      - Description: The person's name
        Name: name
        Type: Text
      - Description: The person's age
        Name: age
        Type: Integer
      label: Generate Text
      model:
      - preset:performance
      prompt_template:
      - definition:
          content:
          - attrs: null
            content:
            - attrs: null
              content: null
              marks: null
              text: ggg
              type: text
            marks: null
            text: null
            type: paragraph
          type: doc
        text: ggg
    type: TextGenerationV8Node
  - connector_config:
      inputs:
      - allow_empty: false
        definition:
          data_type: str
          is_list: false
        description: null
        keys:
        - Input 1
        label: Inputs
        manual: true
        name: variables
        optional: true
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: variable_connector
        visible: true
      outputs:
      - definition:
          data_type: str
          is_list: false
        description: null
        label: Output
        name: output
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: connector
        visible: true
      - definition:
          data_type: str
          is_list: false
        description: null
        label: On error
        name: on_error
        optional: false
        propagates_list: true
        rules: []
        tool_argument: false
        tool_argument_description: null
        tool_argument_optional: false
        tool_mode: hidden
        type: connector
        visible: false
    display:
      position:
        x: 1044.0833333333333
        y: 686.5
      size: {}
    id: df73dd09-49a5-4db6-8a20-cf31f594dad5
    name: Join paths
    node_config: {}
    type: OrNode
