apiVersion: noxus/v4
kind: flow
metadata:
  description: null
  id: 0e42ed06-a56c-44c6-a653-1aa1e2b722c2
  labels: {}
  name: gt
  slug: gt-0e42ed06
schemaVersion: 1
spec:
  edges:
  - source: f1f13ec9-23ff-42cc-b6ce-e3d0deda0315
    source_handle: output
    target: 6cfb2177-5af5-446c-a74e-183081f31920
    target_handle: input
  - source: 6cfb2177-5af5-446c-a74e-183081f31920
    source_handle: output
    target: 38e755b1-53d9-4de1-b17b-c4b5e71866fb
    target_handle: input
  flow_version: v2
  nodes:
  - display:
      position:
        x: 223.39999999999998
        y: 389.20000000000005
    id: f1f13ec9-23ff-42cc-b6ce-e3d0deda0315
    name: Input 1
    node_config:
      label: Input 1
    type: InputNodeV2
    variable_bindings: {}
  - display:
      pinned_fields:
      - template
      position:
        x: 643.4
        y: 389.20000000000005
    id: 6cfb2177-5af5-446c-a74e-183081f31920
    name: Combine Text
    node_config:
      template: 'rr :var[f1f13ec9-23ff-42cc-b6ce-e3d0deda0315.output] '
    type: CombineTextV2
    variable_bindings: {}
  - display:
      position:
        x: 1063.4
        y: 389.20000000000005
    id: 38e755b1-53d9-4de1-b17b-c4b5e71866fb
    name: Output 1
    node_config:
      label: Output 1
      value: :var[6cfb2177-5af5-446c-a74e-183081f31920.text_output]
    type: OutputNodeV2
    variable_bindings: {}
